# Generated by Django 3.0.4 on 2020-03-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Question', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
