# Generated by Django 3.0.4 on 2020-03-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Question', models.CharField(max_length=100)),
            ],
        ),
    ]
