# Generated by Django 3.0.4 on 2020-03-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('wtv', 'How are you today?'), ('stfu', "what's up?"), ('wtf', 'How do you do?')], default='stfu', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question',
            field=models.CharField(max_length=50),
        ),
    ]
